version: '3.7'

services:
  #  express:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    volumes:
  #      - ./src/:/home/mint-kit/src
  #    ports:
  #      - '3000:3000'
  #    environment:
  #      - MONGODB_URL=mongodb://mongo:27017/mint
  #    depends_on:
  #      - mongo
  #    networks:
  #      - node-network

  mongodb:
    image: mongo:5.0.12
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mint
      - MONGO_INITDB_ROOT_PASSWORD=mint123
    restart: on-failure
    networks:
      - node-network

volumes:
  mongodb-data:
    driver: local

networks:
  node-network:
    driver: bridge
